TRAINING_TRIALS: [{level: 4, n_trails: 2}]
START_LEVEL: 5
MAX_REVS: 3
MAX_TRIALS: 10
MIN_LEVEL: 4
MAX_LEVEL: 10

# time in seconds
CONST_TIME: 10
LEVEL_TIME: 2
JITTER_TIME: 1

# visual parameters
TEXT_SIZE: 32
FIG_SIZE: 50
FIG_OFFSET: 10
TASK_POS: [0, 200]
ANSWERS_1_POS: [-250, -150]
ANSWERS_2_POS: [0, -50]
ANSWERS_3_POS: [250, -150]


# clock
## show clock n second before trial end
SHOW_CLOCK: 3
CLOCK_POS: [600, 400]
CLOCK_SIZE: 50

KEYS: ['z', 'x', 'c']